# Generated by Django 3.0.8 on 2021-03-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='../static/network/img/defaulprofile.jpg', upload_to='profile_img', verbose_name='user_photo'),
        ),
    ]
