# Generated by Django 3.0.8 on 2021-03-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='../static/network/img/defaultprofile.jpg', upload_to='profile_img', verbose_name='user_photo'),
        ),
    ]
